FROM node:19-bullseye

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app files
COPY . .

# Build app
RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "dev" ]